using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using Sirenix.OdinInspector;
using System.Security.Cryptography;

[CreateAssetMenu(fileName = "Word Level SO", menuName = "Word Game/Create Level")]
public class WordLevelScriptableObject : SerializedScriptableObject
{
    public string levelID;

    [Header("Letters")]
    public string[] letters;

    [Header("Phrase/Quote")]
    public string keyword;
    public string endLevelLine;

    [Header("Words")]
    [InfoBox("AUTO GENERATED BY DESIGN GRID", InfoMessageType.Error)]
    public WordObject[] words;


    public List<string> GetActiveTileIDs()
    {
        List<string> ids = new List<string>();

        for (int i = 0; i < words.Length; i++)
        {
            for (int k = 0; k < words[i].letters.Length; k++)
            {
                string coord = words[i].letters[k].gridCoords.x + "x" + words[i].letters[k].gridCoords.y;

                if (!ids.Contains(coord))
                {
                    ids.Add(coord);
                }
            }
        }

        return ids;
    }

    public List<string> GetRequiredTileIDs()
    {
        List<string> ids = new List<string>();

        for (int i = 0; i < words.Length; i++)
        {
            for (int k = 0; k < words[i].letters.Length; k++)
            {
                if (words[i].isRequired)
                {
                    string coord = words[i].letters[k].gridCoords.x + "x" + words[i].letters[k].gridCoords.y;

                    if (!ids.Contains(coord))
                    {
                        ids.Add(coord);
                    }
                }

            }
        }

        return ids;
    }

    public WordObject GetWordObject(string input)
    {
        for (int i = 0; i < words.Length; i++)
        {
            if (words[i].word == input)
            {
                return words[i];
            }
        }

        return null;
    }

    [Button]
    void SetBonusWordLetterIDs()
    {
        for (int i = 0; i < words.Length; i++)
        {
            if (words[i].isRequired == false)
            {
                for (int k = 0; k < words[i].letters.Length; k++)
                {
                    words[i].letters[k].gridCoords = new Vector2Int(99, 99);
                }
            }
        }
    }

    public string GetAlphabetTileLetter(string tileId)
    {
        for (int i = 0; i < words.Length; i++)
        {
            for (int k = 0; k < words[i].letters.Length; k++)
            {
                string coord = words[i].letters[k].gridCoords.x + "x" + words[i].letters[k].gridCoords.y;
                if (coord == tileId)
                {
                    return words[i].letters[k].letter;
                }
            }
        }
        return null;
    }

}
